package com.radarqr.dating.android.utility

enum class EditProfileGeneralContentTypes {
    NAME,USERNAME, GENDER, AGE, HEIGHT, WEIGHT, LOCATION, ZODIAC_SIGN, DRINKING, SMOKING,FRIENDLY_420, LOOKING_FOR, CHILDREN, ETHNICITY,
    JOB,JOB_TITLE,SCHOOL, EDUCATION_LEVEL, I_WANT_TO_MEET, AGE_RANGE, HEIGHT_PREF,MAX_DISTANCE
}